-- 004_disable_rls.sql
-- Desabilitar RLS completamente (desenvolvimento)

ALTER TABLE usuario DISABLE ROW LEVEL SECURITY;
ALTER TABLE cliente DISABLE ROW LEVEL SECURITY;
ALTER TABLE ordem_servico DISABLE ROW LEVEL SECURITY;
ALTER TABLE equipamento DISABLE ROW LEVEL SECURITY;
ALTER TABLE produto DISABLE ROW LEVEL SECURITY;
ALTER TABLE item_os DISABLE ROW LEVEL SECURITY;
ALTER TABLE venda DISABLE ROW LEVEL SECURITY;
ALTER TABLE item_venda DISABLE ROW LEVEL SECURITY;
ALTER TABLE documento DISABLE ROW LEVEL SECURITY;
ALTER TABLE movimento_estoque DISABLE ROW LEVEL SECURITY;
